dist: bionic
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - PIP_USE_MIRRORS=true
before_install:
  - pip install poetry
install: poetry install
script:
  - poetry run make lint
  - poetry run make test
